# Generated by Django 5.0 on 2023-12-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitch',
            name='team',
            field=models.CharField(max_length=100),
        ),
    ]
