# Generated by Django 5.0 on 2024-01-01 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0002_alter_pitch_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
