# Generated by Django 5.0 on 2023-12-19 12:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0001_initial'),
        ('criteria', '0001_initial'),
        ('pitches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('teacher_weight_score', models.DecimalField(decimal_places=2, default=1, max_digits=3)),
                ('student_weight_score', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('mode', models.CharField(choices=[('asynchronous', 'Asynchronous'), ('synchronous', 'Synchronous')], default='synchronous', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('course', models.PositiveBigIntegerField()),
                ('video', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comments', models.ManyToManyField(blank=True, to='comments.comment')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('presentors', models.ManyToManyField(to='pitches.pitch')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=3)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criteria.criteria')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting')),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='criterias',
            field=models.ManyToManyField(through='meetings.MeetingCriteria', to='criteria.criteria'),
        ),
    ]
