# Generated by Django 5.0 on 2023-12-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_alter_meeting_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingcriteria',
            name='meeting',
        ),
    ]
