# Generated by Django 5.0 on 2023-12-19 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_remove_meetingcriteria_meeting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='criterias',
        ),
    ]
