# Generated by Django 5.0 on 2023-12-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_remove_meeting_criterias'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='criterias',
            field=models.ManyToManyField(to='meetings.meetingcriteria'),
        ),
    ]
