# Generated by Django 5.0 on 2023-12-19 10:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('identifier', models.CharField(max_length=50, unique=True)),
                ('base_url', models.URLField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
