# Generated by Django 5.0 on 2023-12-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='token',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
