# Generated by Django 5.0 on 2023-12-19 13:13

import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='token',
            field=models.CharField(default=services.models.service_token_generator, max_length=128, unique=True),
        ),
    ]
