# Generated by Django 5.0 on 2024-01-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='role',
            field=models.CharField(choices=[('system', 'System'), ('assistant', 'Assistant'), ('user', 'User')], max_length=20),
        ),
    ]
